title: Spread The World
description: Spreading the world through computer literacy.
baseurl: "" 
url: "https://spreadtheworld.org"
theme: minima  #maybe change?

# This will add pages to your header navigation (works with themes that support it)
header_pages:
  - index.md
  - blog.html
  - mission.md
  - donate.md

