title: Rocket Dan's Site
description: A personal webpage with a blog, mission page, and donate page.
baseurl: "" # leave empty if the site is at the root
url: "https://rocketdan11.github.io"
theme: minima  # you can choose another theme if you prefer

# This will add pages to your header navigation (works with themes that support it)
header_pages:
  - index.md
  - blog.html
  - mission.md
  - donate.md

